### ISSUE TITLE
config.app

### ISSUE THREAD

**Issue by snzmnrdn** [nailsapp/skeleton-app#1]
Missing config/app.php; please run installer.

Which one i should run ?

**Comment by hellopablo** [comment]
hi @aa6my!

You'll need to run the Nails installer, easiest way is by using the [Command Line Tool](https://github.com/nailsapp/command-line-tool) then executing:

```
nails install
```

Alternatively you can run the console manually using the below, however it's likely this will be removed soon as the Command Line Tool matures.

```
./nails.php install
```

Bit of a warning though; Nails will be going through a lot of [breaking] changes over the next few months! It's still in pre-release and a few bits of the core and the core modules haven't been finalised. Feel free to open tickets for the relevant modules if needed and I'll help where I can.

Good luck :)
